### ISSUE TITLE
"is-stream" is an ESM package and cannot be used in the .cjs bundle

### ISSUE THREAD

**Issue by monsonjeremy** [torusresearch/solana-embed#31]
`is-stream` version `3.0.0` is an ESM only package, therefore when used in the CJS bundle untranspiled it causes errors in webpack/next-js/etc... This library should likely use `^2.0.0` or ship only a `.esm` bundle.

**Comment by metallicalfa2** [comment]
@ieow

**Comment by ieow** [comment]
@monsonjeremy is right.
downgrade `is-stream` to `^2.0.0`

**Comment by pgarciaegido** [comment]
Hey guys, 

When are you guys releasing the fix for this? Any way we can overcome this without a release from you guys?

Thanks a lot!!!

**Comment by ieow** [comment]
I think the better way to load embed using dynamic loading.

check this PR
https://github.com/solana-labs/dapp-scaffold/pull/154

**Comment by ieow** [comment]
#32 is merged
