### ISSUE TITLE
How to use the browser version?

### ISSUE THREAD

**Issue by alexandr-kazakov** [torusresearch/solana-embed#50]
I connect it like this:
`<script src="https://unpkg.com/@toruslabs/solana-embed"></script>`
But how to use it?  You have only one example and it's for Vue, how to use it on native JS?

FYI This version works fine for me:
https://unpkg.com/@toruslabs/torus-embed - the global variable **Torus** appears.

**Comment by ieow** [comment]
I am sorry for late reply.
you could use it like this
```
<script src="https://unpkg.com/@toruslabs/solana-embed"></script>
```
```
<script>
  window.torus = new window.SolanaEmbed.default()
  window.torus.init();
</script>
```
