### ISSUE TITLE
Getting Error trying to connect

### ISSUE THREAD

**Issue by truedrju** [torusresearch/solana-embed#57]
I am unable to connect using solana-embed getting error in console

code: -32603
data: {originalError: 'Internal JSON-RPC error.'}
message: "Internal JSON-RPC error."

I am not sure if this is intermittent?

I have tried multiple browsers, useing solana-embed v0.2.1

Seems to not be due to network as I have just tried conecting using tor us provider on MagicEden

**Comment by ieow** [comment]
May I know the code you use to connect ?
